version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cat_network

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - DB_HOST=db
      - DB_USER=cat_user
      - DB_PASSWORD=cat_pass
      - DB_NAME=kattenasiel
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cat_network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kattenasiel
      MYSQL_USER: cat_user
      MYSQL_PASSWORD: cat_pass
    ports:
      - "3306:3306"
    networks:
      - cat_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  db_data:

networks:
  cat_network:
    driver: bridge